---
title: "Python Tutorial"
format: html
---


# Python Overview
## Packages

Some software comes with everything pre-installed.  Python allows the user to customize how much of the software is loaded.  
We will load various required packages as:

``` {.python}
# Load numpy package
import numpy

# Alternative 

```

## Jupyter Notebooks

Jupyter notebook tips

`ctrl` + `enter`: Run current cell
`esc`: Exit current cell
`esc` + `m`: make current cell a markdown cell
`esc` + `y`: make current cell a code cell
`ctrl` + `shift` + `_`: Split current cell in two
`esc` + `a`: add cell above
`esc` + `b`: add cell below
`ctrl` + `/`: comment (in VS Code)
`esc` + `dd`: delete current cell


In code:
- Use `#` to start a line for comments

### Markdown basics
- `#` is biggest font
- `##` is a bit smaller
- `###` is even smaller
- Basic LaTeX style math writing
  - Enclose math in `$`
  - `a_t` for $a_t$
  - `a^2` for $a^2$
  - Use braces for longer sub- and super-scripts `a_{i,t}` is $a_{i,t}$



## Lists

``` {.python}
# This is a list  
import matplotlib.pyplot as plt
plt.plot([1,23,2,4])
plt.show()
```

## Dicts
## Writing Functions
## Simulating random variables
- univariate normal
- multivariate normal
## Numpy financial

## Intro to Pandas
- DataFrames
  - creating dataframes
  - columns
  - index
- Accessing rows, columns, and cells
.loc vs .iloc
- Heirarchical indexing
pd.MultiIndex.from_product(LIST of LISTS)

- Subsetting data
df_subset = df[(df.company_symbol==ticker) & (df.DATE==date)]

## Pandas Formatting

- entire dataframe
`pd.options.display.float_format = '{:.2f}'.format`

# format_mapping = {'price': '${:,.2f}'', 
#                   'coupon_rate': '{:,.2%}'', 
#                   'maturity': '{:,.1f}'',
#                   'face': '${:,.0f}'',
#                   'period': '{:,.0f}''}

# for key, value in format_mapping.items():
#     df[key] = df[key].apply(value.format)

## Working with Data
- Fetching Data
  - pandas_datareader
    - FRED
    - Fama-French
    - FactSet

- 
- Summarizing Data
  - describe
  - 
- Plotting Data
- Regression
- Sorting
- Grouping Data
  - lambda functions and apply
