---
title: 'Asset Classes: Bonds'
author: "<br>Kevin Crotty<br>BUSI 448: Investments"
format: 
    revealjs:
        incremental: true
        logo: RiceLogo.png
        footer: "BUSI 448"
        self-contained: true
        code-fold: true
        theme: [default, custom.scss]
        show-slide-number: print
        menu: 
            width: wide
            numbers: true             
execute:
    echo: true
    freeze: auto
jupyter: python3
---


## Where are we?
**Last time**:

::: {.nonincremental}
- Asset Classes: Equities
:::

. . . 

**Today**:

::: {.nonincremental}
- Asset Classes: Bonds
- Term Structure
- Spot Rates
:::


# Money markets

## Money markets

- Markets for short-term borrowing, usually a year or less
- Sometimes large denomination ($\ge$ $1 million)
- Commonly 3 months or less

. . . 

We will focus on: 

- Treasury Bills
- Repos
- Commercial Paper
<!-- - Money Market Mutual Funds
- Shadow Banking System -->

## Participants (1)

- Commercial banks
  - borrow to fun loan portfolios + satisfy reserve reqs
  - dealers in OTC interest rate derivatives
- Corporations
  - commercial paper
  - banker's acceptance
- Gov'ts (federal, state, municipal) + GSEs
  - Treasury bills

## Participants (2)
- Federal Reserve
  - buy/sell Tbills in open-market operations
  - discount windo and rate affects federal funds rate (interbank lending)
- Brokers + dealers
  - dealers use repos to finance inventory
  - brokers match buyers + sellers (for commission)
- MM mutual funds
  - buy money market instruments on behalf of fund investors

## Treasury Bills

- Short-term borrowing by the US Government
- Maturity of 1 year or less (1, 3, 6, 12 months)
- Usually issued as **discount securities**
- Default risk-free 
- Extremely liquid – can convert to cash at low cost/quickly
- Taxes – exempt from state and local income taxes
- Small denomination – can purchase in $100 increments from [Treasury Direct](https://www.treasurydirect.gov/)

## Historical yields

- can pull data from FRED at St. Louis Fed
- [3-month Tbill series](https://fred.stlouisfed.org/series/TB3MS)

. . .

``` {.python}
import pandas as pd
from pandas_datareader import DataReader as pdr
y3mo = pdr("TB3MS", "fred", start="1929-12-01")
```

<!-- ## {background-iframe="https://fred.stlouisfed.org/series/TB3MS" background-interactive="True"} -->



# Fixed income markets

## Fixed income markets

We will focus on: 

- Treasury notes and bonds
- Corporate bonds

## {background-iframe="https://www.sifma.org/resources/research/fixed-income-chart/" background-interactive="True"}


## {background-iframe="http://bbcx-investments.com/risk/sbb" background-interactive="True"}


## {background-iframe="http://bbcx-investments.com/risk/sbb" background-interactive="True"}


## {background-iframe="http://bbcx-investments.com/risk/asset-classes" background-interactive="True"}

