---
title: 'Short-Selling'
author: "<br>Kevin Crotty<br>BUSI 448: Investments"
format: 
    revealjs:
        incremental: true
        logo: RiceLogo.png
        footer: "BUSI 448"
        self-contained: true
        code-fold: true
        theme: [default, custom.scss]
        show-slide-number: print
        menu: 
            width: wide
            numbers: true
        menu: 
            width: wide
            numbers: true                 
execute:
    echo: true
    freeze: auto
jupyter: python3
---

## Short-selling

- It is possible to sell before you buy.

- You need to borrow the asset you want to sell and return it later.

- This is called selling short or shorting.

- Hope is to reverse order of "buy low-sell high" maxim

. . .

Some jargon:

- Long = own something (asset)
- Short = owe something (liability)
- Cover = buying asset after shorting

## Example #1

- Borrow and sell 100 shares of ABC, trading at $60
- ABC drops to $40 and you buy back and return the shares (cover the short).  
- You bought at $40 and sold at $60, so you made $20 per share.
- Risk is that ABC $\uparrow$ and you have to buy back at more than $60

## Margin requirements

- The risk in short-selling is a price *increase*
- Brokers require the cash proceeds and additional margin as a buffer against this risk.
- Reg T: accounts must have 150% of short sale value at initiation
  - 100% comes from the short proceeds
  - add'l percent margin = $\frac{\text{Equity}}{\text{Value of Short Position}}$

## Margin example: short position

Initial balance sheet

+-------------------------+--------+--------------------+--------+
| Assets                           | Liab/Eq                     |
+:========================+=======:+:===================+=======:+
| Short Proceeds          |  6,000 | Short ABC          |  6,000 |
| Margin Assets           |  3,000 | Equity             |  3,000 |
+-------------------------+--------+--------------------+--------+
| Total                   |  9,000 | Total              |  9,000 |
+-------------------------+--------+--------------------+--------+

. . . 

$$\text{Percent Margin} = \frac{3,000}{6,000} = 50\% $$

## Margin example: short position
Suppose price rises to $70:


+-------------------------+--------+--------------------+--------+
| Assets                           | Liab/Eq                     |
+:========================+=======:+:===================+=======:+
| Short Proceeds          |  6,000 | Short ABC          |  7,000 |
| Margin Assets           |  3,000 | Equity             |  2,000 |
+-------------------------+--------+--------------------+--------+
| Total                   |  9,000 | Total              |  9,000 |
+-------------------------+--------+--------------------+--------+

. . .


$$\text{Percent Margin} = \frac{2,000}{7,000} = 28.6\% $$

## When does a margin call occur?

A margin call occurs when:
$$ \frac{\text{Equity}}{\text{Value of Short Position}} < \text{Maintenance Margin}\,.$$

. . .

- This occurs when ABC's price rises, increasing the short-seller's liability.
  - They need to buy the share back in order to return it!


## When does a margin call occur?

- $S_0$ = initial stock value
- $A_0$ = initial assets (short proceeds + margin assets)
- $MM$ = maintenance margin percentage
- $r$ = stock return

. . .

A margin call occurs when:
$$ \frac{A_0 - S_0(1+r)}{S_0(1+r)} < MM\,.$$

. . .

Solving for $r$:
$$ r > \frac{A_0}{S_0(1+MM)} - 1.$$ 

## Margin call example

Initial balance sheet

+-------------------------+--------+--------------------+--------+
| Assets                           | Liab/Eq                     |
+:========================+=======:+:===================+=======:+
| Short Proceeds          |  6,000 | Short ABC          |  6,000 |
| Margin Assets           |  3,000 | Equity             |  3,000 |
+-------------------------+--------+--------------------+--------+
| Total                   |  9,000 | Total              |  9,000 |
+-------------------------+--------+--------------------+--------+

For maintenance margin of 30%, a margin call occurs if stock return is greater than:

$$ \frac{9,000}{6,000(1+0.25)} - 1 = 15.4\%$$


## Relative performance

Sometimes short to bet on **relative** performance.

. . .

Another Example:

- Suppose you are optimistic that Chevron will outperform other energy companies, but not sure what price of oil will do.

. . .

Strategy: buy CVX and short XOM or energy company index (e.g., XLE).


## Example

- Initial capital to invest of $10,000

- Buy $10,000 of CVX and short $10,000 of XOM.

. . .


+---------------+--------+---------------+--------+
| Assets                 | Liab/Eq                |
+:==============+=======:+:==============+=======:+
| CVX           | 10,000 | XOM           | 10,000 |
| Cash          | 10,000 | Equity        | 10,000 |
+---------------+--------+---------------+--------+
| Total         | 20,000 | Total         | 20,000 |
+---------------+--------+---------------+--------+


## Example (cont'd)

Suppose CVX $\uparrow$ 30% and XOM $\uparrow$ 10%

. . .

+---------------+--------+---------------+--------+
| Assets                 | Liab/Eq                |
+:==============+=======:+:==============+=======:+
| CVX           | 13,000 | XOM           | 11,000 |
| Cash          | 10,000 | Equity        | 12,000 |
+---------------+--------+---------------+--------+
| Total         | 23,000 | Total         | 23,000 |
+---------------+--------+---------------+--------+

. . .

The return is 20% (12,000/10,000).

## Stock borrowing fee

- Have to pay stock borrowing fee (usually small).
- Higher for hard to borrow stocks.
- Lending stocks for shorts is a regular business for mutual funds and the like.

## Margin Requirements

- Suppose you have a $100,000 portfolio and you want to add long-short bets like the CVX-XOM example.
- You can add $50,000 long and $50,000 short.
- Fed Reg T: sum of long and short positions cannot exceed twice your equity, when the positions are put on.
- Reg T is for initial margin. Maintenance margin is up to your broker.
- This is a 150/50 portfolio (150% long and 50% short).

## Dividends and interest

- You have to pay the lender dividends paid by the stock.
- Cash proceeds from a short sale are held as collateral.
- How much interest you get on the cash collateral depends on your broker.  Shop around.


## Short-selling and Information

- Short-selling is robustly negatively related to future returns.
- This suggests shorts, on average, are informed traders.

## Recall risk

## Rebate rates and special

## Limits to arbitrage

Palm-3Com example

## Short-selling regulation

- Price tests
- Short-sale bans

