---
title: 'Asset Managers'
author: "<br>Kevin Crotty<br>BUSI 448: Investments"
format: 
    revealjs:
        incremental: true
        logo: RiceLogo.png
        footer: "BUSI 448"
        self-contained: true
        code-fold: true
        theme: [default, custom.scss]
        show-slide-number: print
        menu: 
            width: wide
            numbers: true             
execute:
    echo: true
    freeze: auto
jupyter: python3
---



## Efficient Markets Theory

**Market efficiency**: Prices reflect all available information.  

The "forms" of efficiency differ only in their definition of "all".
- **Weak**: Prices reflect all historical trade data (past prices, trends, volumes, moving averages)
- **Semi-strong**: Prices reflect all publicly available information (SEC filings, news reports, etc.)
- **Strong**: Prices reflect all relevant information (public and private).
  - Grossman & Stiglitz paradox

Note: if markets are strong form efficient, they must also be semi-strong form; if markets are semi-strong form efficient, they must also be weak form efficient.

## Grossman-Stiglitz Paradox

- Suppose all information is already reflected in prices
- If the cost of gathering information is large relative to the benefits that can be derived from trading on that information, investors will have no incentive to perform the necessary analysis.
- If all information is reflected in prices, then there is nothing to be gained from stock analysis.
- If no one has incentive to gather/analyze information, no one will be able to trade on said information.
- If no one can trade on the information, then how does the information get incorporated in the price?  

## Implications for market efficiency

- The same intuition, in principle, applies to semi-strong form and weak-form efficiency:
- If there is nothing to be gained from fundamental analysis, no one will do it.
- If there is nothing to be gained from technical analysis, no one will do it.

. . .

What are the implications for market efficiency?
